# site properties and page defaults
title: Kannan Lab
subtitle: 
description:  the Wilmer Eye Institute, Johns Hopkins School of Medicine, is at the forefront of interdisciplinary research in nanomedicine. Our focus spans various applications of nanomaterials, particularly in targeted drug delivery for ocular and neurodegenerative diseases. Using dendrimers as a platform, our translational research program aims to address challenges in conditions like cerebral palsy and age-related macular degeneration.
Our team has a track record of innovation, with multiple patents and numerous peer-reviewed publications. We've been honored with prestigious awards such as the National Science Foundation CAREER and Unilever awards, recognizing the impact of our work. Additionally, Dr. Rangaramanujam's leadership extends to serving on the editorial board of Nanomedicine, further contributing to the advancement of our field.

header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: kranagar1@jhmi.edu
  orcid: 0000-0001-8713-9213
  google-scholar: https://scholar.google.com/citations?user=Z6QBnEsAAAAJ&hl=en
  github: kavi10
  twitter: kavi10
  youtube: kavi10

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
