- id: doi:10.1016/S0378-5173(03)00225-4
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0378517303002254-gr9ab.gif
  description: Lorem ipsum _dolor sit amet_.
  buttons:
    - type: source
      link: https://github.com/your-lab/some-repo
  tags:
    - biology
    - big data
    - medicine
