# Latest
- id: doi:10.1016/S0378-5173(03)00225-4
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0378517303002254-gr9ab.gif
  description: Highly branched, functionalized polymers have potential to act as efficient drug carrier systems.
  buttons:
    - type: source
      link: https://www.sciencedirect.com/science/article/pii/S0378517303002254?via%3Dihub
  tags:
    - biology
    - medicine




