# Latest
- id: doi:10.1016/S0378-5173(03)00225-4
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0378517303002254-gr9ab.gif
  description: Highly branched, functionalized polymers have potential to act as efficient drug carrier systems.
  buttons:
    - type: source
      link: https://www.sciencedirect.com/science/article/pii/S0378517303002254?via%3Dihub
  tags:
    - biology
    - medicine

- id: pubmed:20116448
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1359644610000334-gr1.jpg
  title: Dendrimer-based drug and imaging conjugates: design considerations for nanomedical applications
  description: Dendrimers are versatile polymer nanocontainers for drug delivery and imaging, playing key roles in drug efficacy and cellular transport with applications in translational research.
  buttons:
    - type: source
      link: https://pubmed.ncbi.nlm.nih.gov/20116448/
  tags:
    - biology
    - medicine

- id: doi:10.1186/s12859-020-03879-7
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs12859-020-03879-7/MediaObjects/12859_2020_3879_Fig1_HTML.png?as=webp
  buttons:
    - type: docs
      text: Documentation
      link: https://docs.isabl.io
  tags:
    - Platform
    - Bioinformatics
    - Biobank

- id: doi:10.1038/s41591-020-1008-z
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41591-020-1008-z/MediaObjects/41591_2020_1008_Fig1_HTML.png?as=webp

- id: doi:10.1056/EVIDoa2200008
  image: https://evidence.nejm.org/cms/10.1056/EVIDoa2200008/asset/6e698239-222b-49ea-baaa-e64268197dfa/assets/images/large/evidoa2200008_f2.jpg
  buttons:
    - type: package
      text: R Package
      link: https://github.com/papaemmelab/ipssm
    - type: website
      text: Calculator
      link: http://www.mds-risk-model.com
  tags:
    - MDS
    - Cancer
    - Hematology
  repo: papaemmelab/ipssm

- id: doi:10.1038/s41467-022-32103-8
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41467-022-32103-8/MediaObjects/41467_2022_32103_Fig3_HTML.png?as=webp

# Highlights

- id: doi:10.1038/ng.2874

- id: doi:10.1038/ncomms6901

- id: doi:10.1093/bioinformatics/btt750

- id: doi:10.1182/blood-2013-08-518886

- id: doi:10.1038/ng.430

- id: doi:10.1182/bloodadvances.2021006325

# Rest of sources

- id: doi:10.1038/s41375-022-01537-w

- id: doi:10.1038/s41375-021-01448-2

